
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.HashMap;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\035\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\003\004\000\002\004\004\000\002\004\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\006\005\000\002\006\007\000\002" +
    "\007\003\000\002\007\002\000\002\010\005\000\002\010" +
    "\003\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\005\000\002\011\005\000\002\011\003\000" +
    "\002\012\012\000\002\015\005\000\002\015\005\000\002" +
    "\015\005\000\002\015\005\000\002\013\015\000\002\014" +
    "\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\006\003\004\004\005\001\002\000\004\005" +
    "\112\001\002\000\004\006\011\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\004\005\111\001" +
    "\002\000\012\006\022\025\023\027\014\031\012\001\002" +
    "\000\004\017\106\001\002\000\016\005\ufffc\006\ufffc\016" +
    "\ufffc\025\ufffc\027\ufffc\031\ufffc\001\002\000\004\017\074" +
    "\001\002\000\016\005\ufffa\006\ufffa\016\ufffa\025\ufffa\027" +
    "\ufffa\031\ufffa\001\002\000\016\005\ufffb\006\ufffb\016\ufffb" +
    "\025\ufffb\027\ufffb\031\ufffb\001\002\000\016\005\ufff8\006" +
    "\ufff8\016\ufff8\025\ufff8\027\ufff8\031\ufff8\001\002\000\016" +
    "\005\ufff9\006\ufff9\016\ufff9\025\ufff9\027\ufff9\031\ufff9\001" +
    "\002\000\014\005\ufffe\006\022\025\023\027\014\031\012" +
    "\001\002\000\004\010\063\001\002\000\004\017\024\001" +
    "\002\000\010\006\026\007\025\017\027\001\002\000\004" +
    "\023\061\001\002\000\020\011\uffec\012\uffec\013\uffec\014" +
    "\uffec\022\uffec\023\057\024\uffec\001\002\000\006\006\040" +
    "\017\027\001\002\000\004\020\047\001\002\000\016\011" +
    "\037\012\033\013\035\014\032\022\034\024\036\001\002" +
    "\000\006\006\040\017\027\001\002\000\006\006\040\017" +
    "\027\001\002\000\006\006\040\017\027\001\002\000\006" +
    "\006\040\017\027\001\002\000\006\006\040\017\027\001" +
    "\002\000\006\006\040\017\027\001\002\000\034\005\uffec" +
    "\006\uffec\011\uffec\012\uffec\013\uffec\014\uffec\016\uffec\020" +
    "\uffec\022\uffec\024\uffec\025\uffec\027\uffec\031\uffec\001\002" +
    "\000\034\005\ufff1\006\ufff1\011\ufff1\012\033\013\ufff1\014" +
    "\ufff1\016\ufff1\020\ufff1\022\ufff1\024\ufff1\025\ufff1\027\ufff1" +
    "\031\ufff1\001\002\000\014\011\037\012\033\013\035\014" +
    "\032\020\uffe9\001\002\000\034\005\uffef\006\uffef\011\uffef" +
    "\012\033\013\uffef\014\uffef\016\uffef\020\uffef\022\uffef\024" +
    "\uffef\025\uffef\027\uffef\031\uffef\001\002\000\014\011\037" +
    "\012\033\013\035\014\032\020\uffea\001\002\000\034\005" +
    "\ufff0\006\ufff0\011\ufff0\012\ufff0\013\ufff0\014\ufff0\016\ufff0" +
    "\020\ufff0\022\ufff0\024\ufff0\025\ufff0\027\ufff0\031\ufff0\001" +
    "\002\000\034\005\uffee\006\uffee\011\uffee\012\033\013\uffee" +
    "\014\uffee\016\uffee\020\uffee\022\uffee\024\uffee\025\uffee\027" +
    "\uffee\031\uffee\001\002\000\004\026\050\001\002\000\004" +
    "\015\051\001\002\000\012\006\022\025\023\027\014\031" +
    "\012\001\002\000\014\006\022\016\054\025\023\027\014" +
    "\031\012\001\002\000\016\005\ufffd\006\ufffd\016\ufffd\025" +
    "\ufffd\027\ufffd\031\ufffd\001\002\000\016\005\uffeb\006\uffeb" +
    "\016\uffeb\025\uffeb\027\uffeb\031\uffeb\001\002\000\014\011" +
    "\037\012\033\013\035\014\032\020\056\001\002\000\034" +
    "\005\uffed\006\uffed\011\uffed\012\uffed\013\uffed\014\uffed\016" +
    "\uffed\020\uffed\022\uffed\024\uffed\025\uffed\027\uffed\031\uffed" +
    "\001\002\000\006\006\040\017\027\001\002\000\014\011" +
    "\037\012\033\013\035\014\032\020\uffe7\001\002\000\006" +
    "\006\040\017\027\001\002\000\014\011\037\012\033\013" +
    "\035\014\032\020\uffe8\001\002\000\010\006\040\015\065" +
    "\017\027\001\002\000\026\005\ufff7\006\ufff7\011\037\012" +
    "\033\013\035\014\032\016\ufff7\025\ufff7\027\ufff7\031\ufff7" +
    "\001\002\000\006\007\066\016\ufff4\001\002\000\006\016" +
    "\ufff2\021\ufff2\001\002\000\004\016\073\001\002\000\006" +
    "\016\ufff5\021\071\001\002\000\004\007\072\001\002\000" +
    "\006\016\ufff3\021\ufff3\001\002\000\016\005\ufff6\006\ufff6" +
    "\016\ufff6\025\ufff6\027\ufff6\031\ufff6\001\002\000\004\006" +
    "\075\001\002\000\004\020\076\001\002\000\004\030\077" +
    "\001\002\000\004\017\100\001\002\000\006\006\040\017" +
    "\027\001\002\000\014\011\037\012\033\013\035\014\032" +
    "\020\102\001\002\000\004\015\103\001\002\000\012\006" +
    "\022\025\023\027\014\031\012\001\002\000\014\006\022" +
    "\016\105\025\023\027\014\031\012\001\002\000\016\005" +
    "\uffe6\006\uffe6\016\uffe6\025\uffe6\027\uffe6\031\uffe6\001\002" +
    "\000\006\006\040\017\027\001\002\000\014\011\037\012" +
    "\033\013\035\014\032\020\110\001\002\000\016\005\uffe5" +
    "\006\uffe5\016\uffe5\025\uffe5\027\uffe5\031\uffe5\001\002\000" +
    "\004\002\000\001\002\000\004\002\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\004\002\005\001\001\000\002\001\001\000" +
    "\004\003\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\004\020\005\012\006\015\012" +
    "\014\013\017\014\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\005\052" +
    "\006\015\012\014\013\017\014\016\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\011\030\015\027\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\054\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\045" +
    "\001\001\000\004\011\044\001\001\000\004\011\043\001" +
    "\001\000\004\011\042\001\001\000\004\011\041\001\001" +
    "\000\004\011\040\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\004\051\005\012\006\015\012\014" +
    "\013\017\014\016\001\001\000\014\005\052\006\015\012" +
    "\014\013\017\014\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\057\001\001\000\002\001\001\000\004\011\061\001\001" +
    "\000\002\001\001\000\004\011\063\001\001\000\002\001" +
    "\001\000\006\007\066\010\067\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\100\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\004\103\005\012\006\015\012\014\013\017\014\016\001" +
    "\001\000\014\005\052\006\015\012\014\013\017\014\016" +
    "\001\001\000\002\001\001\000\004\011\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s) {
        System.err.println("Error Sintactico en la Linea " + (s.left) + " Columna " + (s.right) + ". Texto: '" + s.value + "'");
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        System.err.println("Error Fatal. El analisis se detuvo en la Linea " + (s.left) + " Columna " + (s.right) + ".");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


    // Aqui vive nuestra Tabla de Simbolos
    public static HashMap<String, String> tablaSimbolos = new HashMap<>();

    // Metodo para imprimir la tabla al terminar con exito
    public void imprimirTabla() {
        System.out.println("\n==========================================");
        System.out.println("           TABLA DE SIMBOLOS              ");
        System.out.println("==========================================");
        System.out.printf("%-20s | %-15s\n", "IDENTIFICADOR", "TIPO/ESTADO");
        System.out.println("------------------------------------------");
        tablaSimbolos.forEach((id, valor) -> 
            System.out.printf("%-20s | %-15s\n", id, valor)
        );
        System.out.println("==========================================");
    }

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= SET_START programa SET_END 
            {
              Object RESULT =null;
		 imprimirTabla(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= error SET_END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= IDENTIFICADOR lista_sentencias 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
               tablaSimbolos.put(nombre, "Nombre Programa"); 
           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= declaracion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= condicion_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= ciclo_para 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= funcion_venn 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracion_conjunto ::= IDENTIFICADOR ASIGNACION expresion_conjunto 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
                           tablaSimbolos.put(id, "Conj. (Operacion)"); 
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_conjunto",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_conjunto ::= IDENTIFICADOR ASIGNACION LLAVE_A elementos_opcional LLAVE_C 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 
                           tablaSimbolos.put(id, "Conj. (Explicito)"); 
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_conjunto",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // elementos_opcional ::= lista_elementos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("elementos_opcional",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // elementos_opcional ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("elementos_opcional",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_elementos ::= lista_elementos COMA NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_elementos",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_elementos ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_elementos",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expresion_conjunto ::= expresion_conjunto UNION expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expresion_conjunto ::= expresion_conjunto INTERSECCION expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion_conjunto ::= expresion_conjunto DIFERENCIA expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion_conjunto ::= expresion_conjunto DIF_SIMETRICA expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion_conjunto ::= PAR_A expresion_conjunto PAR_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion_conjunto ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_conjunto",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion_if ::= SI PAR_A expresion_relacional PAR_C ENTONCES LLAVE_A lista_sentencias LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion_if",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion_relacional ::= expresion_conjunto IGUALDAD expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_relacional",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion_relacional ::= expresion_conjunto CONTENCION expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_relacional",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion_relacional ::= NUMERO PERTENENCIA expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_relacional",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion_relacional ::= IDENTIFICADOR PERTENENCIA expresion_conjunto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion_relacional",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ciclo_para ::= PARA_CADA PAR_A IDENTIFICADOR PAR_C EN PAR_A expresion_conjunto PAR_C LLAVE_A lista_sentencias LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ciclo_para",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // funcion_venn ::= VENN PAR_A expresion_conjunto PAR_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion_venn",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
